### ISSUE TITLE
Build failing in Xcode

### ISSUE THREAD

**Issue by pklink1337** [sctplab/SCTP_NKE_HighSierra#2]
Hey there,

I tried building the repository using Xcode and received the following error:
No member named 'socket' in 'struct xsctp_inb'

The error is provoked by lines 519-521 in sctp_sysctl.c:
#if !(defined(__FreeBSD__) && (__FreeBSD_version < 1001517))
		xinpcb.socket = (uintptr_t)inp->sctp_socket;
#endif

Since I'm building Mac OS and not on FreeBSD I guess it is correct that this code snippet gets 'included' by the precompiler right?

Best and thanks in advance,
Pascal

**Comment by tuexen** [comment]
Fix in https://github.com/sctplab/SCTP_NKE_HighSierra/commit/12b223daf1185394a9c1df56999ed9945df5c92b.
Thanks for reporting!
