### ISSUE TITLE
SCTP_NKE for Mojave

### ISSUE THREAD

**Issue by pklink1337** [sctplab/SCTP_NKE_HighSierra#4]
Hello,

after updating my OS to Mojave I was wondering if a SCTP_NKE Version for Mojave is currently planned. If not, are there any information what would need to be changed in the HighSierra Version to make it work with Mojave? I am everything else than an expert in Xcode or OS X kernel extensions but if the changes are restricted to changing some version flags I'm sure that I could make it work myself.

Best
Pascal

**Comment by pklink1337** [comment]
I see! Thank you very much for the information I will try using the High Sierra version the next day and report the results!

**Comment by william86370** [comment]
I just saw this issue and having an SCTP for Mojave would be really useful I also believe the Opensource website now has the kernel for 10.14 https://opensource.apple.com/release/macos-1014.html

**Comment by tuexen** [comment]
It still says:
```
xnu-4903.201.2 (coming soon!) | -
```
